[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.21'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./"}]

[fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
